"""
optimization/mock_data.py
==========================
Heuristic mock candidate generator for the recommended MVP campus:

  300 × 300 m site
  ┌────────────────────────────────────────────┐
  │  2 Academic Buildings  (60 × 40 m)         │
  │  3 Hostels             (50 × 30 m)         │
  │  1 Library             (30 × 25 m)         │
  │  1 Administration      (40 × 30 m)         │
  │  1 Sports Complex      (80 × 60 m)         │
  │  1 Parking Area        (40 × 30 m)         │
  └────────────────────────────────────────────┘

Candidates are generated by randomly perturbing a base layout with grid snapping,
ensuring a reasonable variety of valid and slightly-invalid configurations.

This module requires no P2 output — it replaces the GNN for local testing.
"""
from __future__ import annotations

import random
import uuid
from typing import List

from optimization.contracts import (
    CandidateBuilding,
    CandidateLayout,
    CampusRequirements,
    Entrance,
)


# ── Building catalogue for the MVP campus ─────────────────────────────────────

_MVP_BUILDINGS = [
    {"id": 1, "name": "Academic Block A", "type": "academic",  "zone": "academic",     "width": 60, "depth": 40, "height": 18, "floor_count": 4},
    {"id": 2, "name": "Academic Block B", "type": "academic",  "zone": "academic",     "width": 60, "depth": 40, "height": 18, "floor_count": 4},
    {"id": 3, "name": "Library",          "type": "library",   "zone": "academic",     "width": 30, "depth": 25, "height": 12, "floor_count": 3},
    {"id": 4, "name": "Administration",   "type": "admin",     "zone": "admin",        "width": 40, "depth": 30, "height": 12, "floor_count": 3},
    {"id": 5, "name": "Hostel A",         "type": "hostel",    "zone": "residential",  "width": 50, "depth": 30, "height": 15, "floor_count": 5},
    {"id": 6, "name": "Hostel B",         "type": "hostel",    "zone": "residential",  "width": 50, "depth": 30, "height": 15, "floor_count": 5},
    {"id": 7, "name": "Hostel C",         "type": "hostel",    "zone": "residential",  "width": 50, "depth": 30, "height": 15, "floor_count": 5},
    {"id": 8, "name": "Sports Complex",   "type": "sports",    "zone": "sports",       "width": 80, "depth": 60, "height": 10, "floor_count": 1},
    {"id": 9, "name": "Parking Area",     "type": "parking",   "zone": "parking",      "width": 40, "depth": 30, "height":  3, "floor_count": 1},
]


def get_demo_requirements() -> CampusRequirements:
    """Return the standard 300 × 300 demo requirements."""
    return CampusRequirements(
        project_id=1,
        site_width=300.0,
        site_height=300.0,
        min_green_percent=25.0,
        min_parking_percent=10.0,
        min_road_width=8.0,
        min_building_gap=10.0,
        entrances=[
            Entrance(x=145.0, y=0.0, width=12.0),   # south entrance
            Entrance(x=0.0,   y=145.0, width=10.0), # west entrance
        ],
    )


def _base_positions(site_w: float, site_h: float) -> List[dict]:
    """
    Return a sensible base layout.

    Buildings are arranged in functional zones:
      Academic zone: north-west
      Residential:   south
      Admin:         north-east
      Sports:        east
      Parking:       near south entrance
    """
    return [
        {"id": 1, "x": 20,  "y": 210},  # Academic A
        {"id": 2, "x": 90,  "y": 210},  # Academic B
        {"id": 3, "x": 20,  "y": 155},  # Library
        {"id": 4, "x": 220, "y": 210},  # Admin
        {"id": 5, "x": 20,  "y": 30},   # Hostel A
        {"id": 6, "x": 80,  "y": 30},   # Hostel B
        {"id": 7, "x": 140, "y": 30},   # Hostel C
        {"id": 8, "x": 200, "y": 130},  # Sports
        {"id": 9, "x": 200, "y": 20},   # Parking
    ]


def _clamp(val: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, val))


def generate_mock_candidates(
    n: int,
    requirements: CampusRequirements,
    seed: int = 0,
) -> List[CandidateLayout]:
    """
    Generate *n* candidate layouts by perturbing a base layout.

    Parameters
    ----------
    n            : number of candidates.
    requirements : site requirements (used for bounds).
    seed         : random seed for reproducibility.

    Returns
    -------
    list[CandidateLayout] — length == n.
    """
    rng = random.Random(seed)
    sw = requirements.site_width
    sh = requirements.site_height
    gap = requirements.min_building_gap

    base = _base_positions(sw, sh)
    base_map = {b["id"]: b for b in base}

    # Build building info lookup
    bld_info = {b["id"]: b for b in _MVP_BUILDINGS}

    candidates: List[CandidateLayout] = []

    for i in range(n):
        buildings: List[CandidateBuilding] = []

        for bld in _MVP_BUILDINGS:
            bid = bld["id"]
            base_x = base_map[bid]["x"]
            base_y = base_map[bid]["y"]

            # Perturbation: ±50 m, snapped to 5 m grid
            jitter_x = rng.choice(range(-50, 51, 5))
            jitter_y = rng.choice(range(-50, 51, 5))

            # Randomly allow some rotations (0 or 90 degrees)
            rotation = rng.choice([0, 0, 0, 90]) if rng.random() < 0.3 else 0

            w, d = bld["width"], bld["depth"]
            if rotation == 90:
                w, d = d, w  # swap footprint dims when rotated

            x = _clamp(base_x + jitter_x, gap, sw - w - gap)
            y = _clamp(base_y + jitter_y, gap, sh - d - gap)

            buildings.append(
                CandidateBuilding(
                    building_id=bid,
                    x=round(x, 1),
                    y=round(y, 1),
                    rotation=float(rotation),
                    width=float(w),
                    depth=float(d),
                    zone=bld["zone"],
                    name=bld["name"],
                    type=bld["type"],
                    height=float(bld["height"]),
                    floor_count=bld["floor_count"],
                )
            )

        candidates.append(
            CandidateLayout(
                candidate_id=f"mock-{i:04d}",
                site_width=sw,
                site_height=sh,
                buildings=buildings,
            )
        )

    return candidates
